---
defaults: # defaults apply to all gems in the 'gems:' section, but can be overridden
  install_options: --source=http://localhost:8808 --no-rdoc --no-ri
gems:
- name: json
  version: 1.1.2
- name: mechanize
  version: = 0.6.10
  # check_for_upgrade: true
# - name: merb-mailer
#   version: = 0.9.3